### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by obtim** [mg07926/NBA_webscrapper#1]
Python script work fine. But nothing. But the NBA_Teams.* and NBA_Players.* files are empty

**Comment by mg07926** [comment]
On line 22, the NBA.com website changed the class name.
If you change this line:
team_profile = soup.find_all('div', class_= 'flex text-sm') 

to this:
team_profile = soup.find_all('div', class_= 'TeamFigure_tfLinks__i6-eh')

the program should work
